name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Check out the content (source branch)
    - name: Check out source
      uses: actions/checkout@v2

    # Check out the `gh-pages` branch into the `public` directory.
    - name: Check out documentation branch
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'
        path: 'docs/public'

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    # Update npm to latest
    - name: Update npm to latest
      run: npm install -g npm@latest

    # Build the site
    - name: Install npm packages
      run: npm install
    - name: Build documentation
      run: npm run build
      env:
        PREFIX_PATHS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Check for changes; this avoids publishing a new change to the
    # gh-pages branch when we made a change to (for example) a unit test.
    # If there were changes made in the publish step above, then this
    # will set the variable `has_changes` to `1` for subsequent steps.
    - name: Check for changes
      id: status
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "::set-output name=has_changes::1"
        fi
      working-directory: docs/public

    # Commit the changes to the gh-pages branch and push the changes up to
    # GitHub.  (Replace the name and email address with your own.)
    # This step only runs if the previous step set `has_changes` to `1`.
    - name: Publish documentation
      run: |
        git add --verbose .
        git config user.name 'CI User'
        git config user.email 'noreply@npmjs.com'
        git commit -m 'Update from CI'
        git push origin gh-pages
      if: steps.status.outputs.has_changes == '1'
      working-directory: docs/public
